<a href="https://colab.research.google.com/github/shyamalkar/Data_Science/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#``What is Data Preprocessing ? ``

    Data preprocessing is a process where aw data are cleaning here and prepare for machine learning.


    Machine learning engineer are could not use raw data and train to machine .


    Major parts in Data preprocessing Machine learning is preprocessing mainly includes .

        Scaling
        Normalization
        Encoding


    Encoding (Text -> Number)

    Machine can't understand text data .
    So Text convert in a number .

    Example Dataset :

    Kolkata,
    Delhi
    Mumbai

    Label Encoding

    0,
    1,
    2 .

    Code like that .

    from sklearn.preprocessing import LabelEncoder

    #Create encoder object
    encoder = LabelEncoder()

    #Convert text column into numbers
    df["City"] = encoder.fit_transform(df["City"])


``One Hot Encoding``
  
  Better encoding method

  Instead of single number, New columns create .

  code -
      
      from sklearn.preprocessing import OneHotEncoder
      import pandas as pd

      encoder = OneHotEncoder()

      encoded = encoder.fit_transform(df[["City"]]).toarray()

      encoded_df = pd.DataFrame(encoded)

      encoded_df

# ***Feature Scaling***

     Differents column different values.
      e.g.,
          
          Age	 Salary
          25	 50000
          30	 70000

      Problem:
             
             Age = Small number
             Salary = Very large number

             Model give more importence to Salary column ,

             So we use scaling method.

             Standardization (Standard Scaling)
               
               Formula:-
                        
                        Z = (X - Mean)/StandardDeviation

                  Result:
                        
                        Mean = 0
                        Standard Deviation = 1

                 Code
                    
                    from sklearn.preprocessing import StandardScaler

                    scaler = StandardScaler()

                    scaled_data = scaler.fit_transform(df)



``Normalization :-   ``
               
               Normalization usage for data come under 0-1 range .

        Formula:-
                
                X1 = (X - min) / (max - min)
            
            Example:-
                 
                 Age
                  20
                  30
                  40

                  Calculation :-

                    First:-          
                              20 - 20 / 40 - 20 = 0/20
                              = 0
                    
                    Second :-   
                             30 - 20 / 40 - 20
                             = 10 / 20
                             = 0.5

                    Third :- 40 - 20 / 40-20
                              
                            = 20 / 20
                            = 1.0

                  
                Normalized
                    
                  0.0
                  0.5
                  1.0



# ***`Data Preprocessing: Scaling, Encoding, Normalization(With Scikit-Learn )`***
         

         Concept What is Data Preprocessing
            
            Data preprocessing  transform raw data into a clean and usable format .

            It improves model performance and training speed .

            Common tasks:

            Handling missing value
            Scaling numeric features
            Encoding categorical variables
            Normalizing feature ranges


        1️⃣ Feature Scaling

        Scaling adjust values so features contribute equaly .

        Common techniques StandardScaler (Z-Score), MinMaxScaler(0-1 scale)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

#Example Dataset

numeric_data = pd.DataFrame({
    'salary':[20000, 45000, 60000, 120000],
    'Age':[25, 32, 47, 62]
})
numeric_data

   salary  Age
0   20000   25
1   45000   32
2   60000   47
3  120000   62

In [ ]:

from sklearn.preprocessing import StandardScaler, MinMaxScaler

#Standard Scaling (Z-Score)

std_scaler = StandardScaler() #Import standard scaler

scaled_std = std_scaler.fit_transform(numeric_data) #Using std_scaler(variable and StandardScaler function).fit_transform and numeric data variable inside in coding

df = pd.DataFrame(scaled_std, columns=numeric_data.columns) # Here pd.DataFrame usage for output dhow in dataFrame

print('\n Standard Scaled Data: \n ', df)

#How Salary convert into scaler value ? Let's calculate the value . Z-Score-Scaling and Standard scaling both are same .

#What do StandardScaler ?

      #Formula:-      Z = X-Mean/STD

      #Means :-

            #Value - Mean / STD

            #Calculate the salary mean

                #Salary values =  20000, 45000, 60000, 120000

                # Mean :-

                        #(20000, 45000, 60000, 120000 ) / 4 = 61250

                        # Calculate the Difference from mean .

                        #Salary - Mean = 20000 - 61250 = -41250 , 45000 − 61250 = -16250 , 60000	60000 − 61250 = -1250, 120000	120000 − 61250 = 58750 .

                        #Squared Power 2

                        #Value           Square

                         # -41250          1701562500

                         # -16250          264062500

                         # -1250           1562500

                         # 58750            3451562500


                        #Sum 1701562500 + 264062500 + 1562500 + 3451562500 = 5413437500

                        #Calculate the variance, Variance = Sum / n means all calculate number divide by number point

                        # 5413437500 / 4 = 1353359375


                        #Square Root

                                 #std root 1353359375 = 36787

#The main purpose to use z-score for Bringing features to the same scale, main this is we use z score for equal the importance .


#🚨 Importance :-  Where use Scaling and where not ?

                 # Scaling usage for these types of column where this algorithm use distance or gradient . So scale features are very importent .

                 #E.g., -> Distance based algorithms . - > Linear Regression, Logistic Regression, Neural Networks .

                 #Scale are not importent for these algorithm like :- Decision Tree, Random Forest, XGBoost, Light GBM , because Tree algorithm work for sprit rule .


                 #Right thing is :- If algorithm scale sensitive then use scaler

 Standard Scaled Data:
       salary       Age
0 -1.120739 -1.157361
1 -0.441503 -0.666359
2 -0.033962  0.385787
3  1.596204  1.437933

# **`Min Max Scaler`**
     
     Min-Max Scaler

        What is min max scaler ?
           
           min max scaler usage for data represent under 0-1

           e.g.,
              
              Salary - 20000, 45000, 60000, 120000

              After Scaling ->
                            
                            Salary ->
                                   
                                    0.00, 0.25, 0.40, 1.00 .

                                    Lowest value -> 0 , highest -> 1


           Formula :- x' = x - x_min/ x_max - x_min
                
                Means :-   Salary = [20000, 45000, 60000, 120000]

                Minimum value
                      
                      20000

                Max value 120000

            
            Step -1 (20000)

               (20000 - 20000) / (120000 - 20000)
               = 0 / 100000
               = 0

            Step -2 (45000)

            (45000 - 20000) / 100000
            = 25000 / 100000
            = 0.25

            Step -3

            (60000 - 20000) / 100000
            = 40000 / 100000
            = 0.40

            Step - 4

            (120000 - 20000) / 100000
            = 100000 / 100000
            = 1

In [ ]:
minmax_scaler = MinMaxScaler() # We create a Object in MinMaxScaler , Means now we can scale the data using minmax_scaler.

scaled_minmax = minmax_scaler.fit_transform(numeric_data) # minmax_scaler is a function and fit usage for see the data
print('\n Min-Max Scaled Data :\n', pd.DataFrame(scaled_minmax, columns=numeric_data.columns)) # scaled_minmax this is numpy array . this array convert into dataframe. columns=numeric_data.columns it is very importent because this is usage for original dataset copy and copy the column name .

print('\nReal dataset:\n',numeric_data)

 Min-Max Scaled Data :
    salary       Age
0    0.00  0.000000
1    0.25  0.189189
2    0.40  0.594595
3    1.00  1.000000

Real dataset:
    salary  Age
0   20000   25
1   45000   32
2   60000   47
3  120000   62

***`Encoding Categorical variable:-`***
       
       Convert text to numeric format for ML models

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

#Sample data

cat_data = pd.DataFrame({
    'Department':['HR', 'Sales',  'IT', 'HR', 'IT', 'filpa', 'Phil', 'Manami', 'Venami', 'HR', 'Sales',  'IT', 'HR', 'IT', 'filpa', 'Phil', 'Manami', 'Venami']
    })

cat_data

   Department
0          HR
1       Sales
2          IT
3          HR
4          IT
5       filpa
6        Phil
7      Manami
8      Venami
9          HR
10      Sales
11         IT
12         HR
13         IT
14      filpa
15       Phil
16     Manami
17     Venami

#***`Label Encoding`***

In [ ]:
label_encoder = LabelEncoder() # We create a labelEncoder class, Label Encoder usage for text to number convert tool . Now using this object categorical data can be transfer into numeric data .

cat_data['Dept_labe'] = label_encoder.fit_transform(cat_data['Department']) # Here 3 types of work ,cat_data['Department'] this is a dataset column, Department - HR, IT......

#Here both work are done here .
#fit(), first encoder find a unique category .

#transform() , Give's number to category .
#cat_data['Dept_labe'],  create a new column . this is a new column where encoded number presented.

#This print with dataframe .

print("\n Label Encoded: \n", cat_data)

 Label Encoded:
    Department  Dept_labe
0          HR          0
1       Sales          4
2          IT          1
3          HR          0
4          IT          1
5       filpa          6
6        Phil          3
7      Manami          2
8      Venami          5
9          HR          0
10      Sales          4
11         IT          1
12         HR          0
13         IT          1
14      filpa          6
15       Phil          3
16     Manami          2
17     Venami          5

# ***`One Hot Encoding`***
      
      ``What is One Hot Encoding``
          

          ``One Hot Encoding usage for convert text to number and (text / category ) convert into multiple binary columns (0/1), machine learning does't understand text so category convert into number .``



          Model doesn't understand text so we use OneHotEncoder

In [ ]:
cat_data_ohe = pd.get_dummies(cat_data['Department'], prefix='Dept').astype(int) # Usage for add Dept for every category column .

print('\n One Hot Encoded: \n\n:', cat_data_ohe)

 One Hot Encoded:

:     Dept_HR  Dept_IT  Dept_Manami  Dept_Phil  Dept_Sales  Dept_Venami  \
0         1        0            0          0           0            0
1         0        0            0          0           1            0
2         0        1            0          0           0            0
3         1        0            0          0           0            0
4         0        1            0          0           0            0
5         0        0            0          0           0            0
6         0        0            0          1           0            0
7         0        0            1          0           0            0
8         0        0            0          0           0            1
9         1        0            0          0           0            0
10        0        0            0          0           1            0
11        0        1            0          0           0            0
12        1        0            0          0           0            0
13        0        1            0          0           0            0
14        0        0            0          0           0            0
15        0        0            0          1           0            0
16        0        0            1          0           0            0
17        0        0            0          0           0            1

    Dept_filpa
0            0
1            0
2            0
3            0
4            0
5            1
6            0
7            0
8            0
9            0
10           0
11           0
12           0
13           0
14           1
15           0
16           0
17           0

*``What is the difference between Label Encoder and One Hot Encoder
```
*
        Label Encoding -> Label Encoding give a number to every category .

        Example:-
             
             HR
             IT
             Sales

        With Encoding:-
                  
                  HR             0
                  IT             1
                  Sales          2


            Model can be think one order means have a ranking

            Which means most time incorrect .

            One-Hot-Encoding

            One hot encoding create columns for every category .

            Example:-
                  
                  HR
                  IT
                  Sales

              With Encoding :-  
                    
                    Dept_HR   Dept_IT  Dept_Sales
                    1             0       0
                    0             1       0
                    0             0       1

                    No rank here .


              Main difference is :-   

              Label Encoding        OneHotEncoding
                 
      Category -> Singel number     Category -> multibinary columns (0/1)

      model can remember because order have       No order are made.


      Small memory need           Memory usage most .




      E.g.,
          
          Color - > Red, Blue, Green.

          Encoding = Red(0)
                     
                     Blue(1)

                     Green(2)
          
          Model can think:-

          Green > Blue > Red

          One-Hot Encoding

          Red          Blue        Green
          1             0            0
          0             1            0
          0             0            1


          No rank



One Line answer :--
                  Label Encoding converts categories into a single numeric column, while One-Hot Encoding creates separate binary columns for each category to avoid ordinal relationships.



Importent:-

Label Encoding is often used for the target variable (y) in classification problems, while One-Hot Encoding is commonly used for categorical feature variables (X) to avoid introducing ordinal relationships.

# ***`Normalization`***

       What is Normalization ?
             
             Purpose:-
                 
                 Scales each row to have a unit magnitude (length = 1) while preserving direction.


             Key Idea:-
                 Converts row vector into the pure direction from by dividing by their euclidean norm .

             When to use ⁉
                       
                       Text data (Tf-IDF word counts)

                       Clustering (K-means, cousine similarity)

                       Any algorithm sensitive to vector magnitudes but not theirlength (NLP, Recommender system)

In [ ]:
from sklearn.preprocessing import Normalizer

#Example data

X = np.array([[3.0, 4.0], [1.0, 0.0], [0.0, 8.0]])
X

array([[3., 4.],
       [1., 0.],
       [0., 8.]])

In [ ]:
X

array([[3., 4.],
       [1., 0.],
       [0., 8.]])

In [ ]:
normalizer = Normalizer()
normalizer_data = normalizer.fit_transform(X)
print('\n Normalized Data: \n', normalizer_data)

 Normalized Data:
 [[0.6 0.8]
 [1.  0. ]
 [0.  1. ]]

***`How It Works`***

For each row , the normalizer . Computes the Euclidean norm(magnitude)

             norm = sqrt(x one square + x two square + ...)

             Divides each element by the norm:

             x one normalized = x one / norm, x square normalized = x 2 / norm

             calculates row Norm : for [3,4] - >
             norm = root(3 square + 4 square) = root(9 + 16) = 5



             Normalized

             DividesEach Element by Norm: [3/5, 4/5] = [0.6, 0.8].

             Second row :-  [1.0, 0.0] ->
             norm = root(1 square + 0 Square) = 1
             Normalized: [1/1, 0/1] = [1.0, 0.0]

             Thired row :-  [0.0, 8.0]:

             Norm = root ( 0 square + 8 square ) = 8

             Normalized: [0/8, 8/8] = [0.0, 1.0]

***`Case Study: Retail Customer Data`***

Scenario: You have a retail customer dataset with income, age, and gender .

You want to prepare it for ML model input

In [ ]:
raw_data = pd.DataFrame({
    'Customer ID': [101, 102, 103, 104, 105],
    'Name' : ['Sk', 'SB', 'MK', 'SD', 'BM'],
    'Age' : [10, 20, 30, 40, 50],
    'Subject' : ['Ben', 'Eng', 'Math', 'Phil', 'Geo']
})
print('\n this data create by me:\n\n', raw_data)

 this data create by me:

    Customer ID Name  Age Subject
0          101   Sk   10     Ben
1          102   SB   20     Eng
2          103   MK   30    Math
3          104   SD   40    Phil
4          105   BM   50     Geo

In [ ]:
#Drop ID (Notuseful for training)
data = raw_data.drop(columns='Customer ID')
data

  Name  Age Subject
0   Sk   10     Ben
1   SB   20     Eng
2   MK   30    Math
3   SD   40    Phil
4   BM   50     Geo

In [ ]:
#let me show you how to encode gender column

labelencoder = LabelEncoder()
data['Name'] = labelencoder.fit_transform(data['Name'])
data

#gender_One_hot_encoder = One_hot_encoder.fit_transform('Name')
#gender_One_hot_encoder

   Name  Age Subject
0     4   10     Ben
1     2   20     Eng
2     1   30    Math
3     3   40    Phil
4     0   50     Geo

In [ ]:
minmaxscaler = MinMaxScaler()

scaled = minmax_scaler.fit_transform(data[['Age', 'Name']])
data[['Age', 'Name']] = scaled

print('\n processed Retail Data: \n', data)
#data_min_max_scaler = minmaxscaler.fit_transform()

 processed Retail Data:
    Name   Age Subject
0  1.00  0.00     Ben
1  0.50  0.25     Eng
2  0.25  0.50    Math
3  0.75  0.75    Phil
4  0.00  1.00     Geo

# ***`Summary`***

        Scaling (ScalingScaler): Transforms Features to mean = 0, std=1 for consistent magnitudes .

        Encoding(LabelEncoder/OneHot) : Converts categories to number (labels) or binary columns (One-hot).

        Normalization (Normalizer): scales each row to unit magnitude (length=1) for direction-focused analysis .