<a href="https://colab.research.google.com/github/shyamalkar/Data_Science/blob/main/Data_Science_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***`EDA(Exploratory Data Analysis)`***

      Means:-
           
           Explore the data and understand what is the real meaning in data .

           in short:-
                   
                   Process of understand the data . when Data Scientist and analyst gets data first time then they do EDA first for understand better .

                   What is the real meaning of this data ?

                   Have a missing value or not.

                   Outlier or not ?

                   Which Feature is importent ?
                   
                   What is the relation between feature .


``Why invent EDA ? ``
                 
                 Before it's very hard to understand the data and one company collect 10 lakhs customer data. But they don't know

                 Data clean or not ?
                 Data accurate or not ?
                 Column means
                 what is the data distribution .

                 If you predict without clean the data, model give bad response, garbage result -> garbage data

                 So yeahh ! this is the reson why EDA was invent .


``Why use EDA ? ``
                 
                 Data structure understand
                 Missing value detect
                 Outlier Detect #E.g., 23, 45, 34, 23, 24, 56, 400 . So 400 is a Outlier .
                 Feature Relationunderstand
                 Understand the data distribution .
                 Deature selection

``Where use EDA ?``
                 
                 Machine learning
                 Data science
                 Business analytics
                 research

``Main parts in EDA  ``
                 
                 Univariate Analysis → 1 variable

                 Bivariate Analysis → 2 variable

                 Multivariate Analysis → 3+ variable

``Below:-``

                Complete 40 EDA Techniques List:-
                                                  Complete 40 EDA Techniques List
                                                  1️⃣ Data Loading
                                                  1. `pd.read_csv()`
                                                  2. `pd.read_excel()`
                                                  ---
                                                  2️⃣ Data Overview
                                                  3. `df.head()`
                                                  4. `df.tail()`
                                                  5. `df.sample()`
                                                  6. `df.shape`
                                                  7. `df.columns`
                                                  8. `df.info()`
                                                  9. `df.describe()`
                                                  ---
                                                  3️⃣ Data Type Analysis
                                                  10. `df.dtypes`
                                                  11. `select_dtypes()`
                                                  ---
                                                  4️⃣ Missing Value Analysis
                                                  12. `df.isnull()`
                                                  13. `df.isnull().sum()`
                                                  14. `df.isna()`
                                                  ---
                                                  5️⃣ Missing Value Handling
                                                  15. `dropna()`
                                                  16. `fillna()`
                                                  ---
                                                  6️⃣ Duplicate Data
                                                  17. `duplicated()`
                                                  18. `drop_duplicates()`
                                                  ---
                                                  7️⃣ Statistical Analysis
                                                  19. `mean()`
                                                  20. `median()`
                                                  21. `mode()`
                                                  22. `std()`
                                                  23. `min()`
                                                  24. `max()`
                                                  25. `quantile()`
                                                  ---
                                                  8️⃣ Unique Value Analysis
                                                  26. `unique()`
                                                  27. `nunique()`
                                                  28. `value_counts()`
                                                  ---
                                                  9️⃣ Group Analysis
                                                  29. `groupby()`
                                                  ---
                                                  🔟 Pivot Analysis
                                                  30. `pivot_table()`
                                                  ---
                                                  # 11️⃣ Correlation Analysis
                                                  31. `df.corr()
                                                  `---
                                                  12️⃣ Visualization (Matplotlib / Seaborn)
                                                  32. Line Plot
                                                  33. Scatter Plot
                                                  34. Histogram
                                                  35. Bar Plot
                                                  36. Count Plot
                                                  37. Box Plot
                                                  38. Violin Plot
                                                  39. Heatmap
                                                  40. Pairplot

***`Some importent topics must be know for cleaning method`***

All Missing value Remove (One Line)

            All Missing row remove NaN, null remove .

df = df.dropna() # This coding remove missing value, None, NaN .

               Empty space convert into missing .

df = df.replace(r'^\s*$', np.nan, regex=True). #Blank space convert into NaN .

              Column Name Clean + Rename(One Line)

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

             Column Delete (One Line)

df = df.drop(columns=["age","salary"])

             All missing value in One  line

df = df.fillna(0)

***`Data Loading`***

In [ ]:
import pandas as pd

df = pd.read_csv('/content/tourism_data.csv')
df

#df = pd.read_excel('file_name.xlsx')

,Country,Category,Year,Visitors_Millions,Revenue_Billion_USD,Average_Rating
0,Japan,Wildlife,2022,54.08,18.89,3.31
1,Australia,City,2018,13.29,78.18,3.11
2,Australia,Wildlife,2020,0.57,119.07,4.23
3,UAE,Religious,2023,26.57,73.50,3.28
4,Spain,Wildlife,2021,88.50,56.12,4.72
...,...,...,...,...,...,...
295,Japan,Cultural,2023,9.05,74.94,3.90
296,France,City,2015,66.45,103.56,3.43
297,India,Religious,2019,57.96,72.93,4.09
298,UAE,Beach,2023,44.96,118.54,3.27
299,USA,Cultural,2017,40.12,53.61,4.45

***`Data Overview`***

In [ ]:
df.head() # Show first 5 row

,Country,Category,Year,Visitors_Millions,Revenue_Billion_USD,Average_Rating
0,Japan,Wildlife,2022,54.08,18.89,3.31
1,Australia,City,2018,13.29,78.18,3.11
2,Australia,Wildlife,2020,0.57,119.07,4.23
3,UAE,Religious,2023,26.57,73.50,3.28
4,Spain,Wildlife,2021,88.50,56.12,4.72

In [ ]:
df.tail() # to see dataset last 5 rows

,Country,Category,Year,Visitors_Millions,Revenue_Billion_USD,Average_Rating
295,Japan,Cultural,2023,9.05,74.94,3.90
296,France,City,2015,66.45,103.56,3.43
297,India,Religious,2019,57.96,72.93,4.09
298,UAE,Beach,2023,44.96,118.54,3.27
299,USA,Cultural,2017,40.12,53.61,4.45

In [ ]:
df.sample() # See random row

,Country,Category,Year,Visitors_Millions,Revenue_Billion_USD,Average_Rating
150,Italy,Wildlife,2019,83.06,84.93,3.31

In [ ]:
df.shape #How many column and row have in this dataset know this .

(300, 6)

In [ ]:
df.columns # See all column name

Index(['Country', 'Category', 'Year', 'Visitors_Millions',
       'Revenue_Billion_USD', 'Average_Rating'],
      dtype='object')

In [ ]:
df.info() #To see datatype, non-null count

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country              300 non-null    object
 1   Category             300 non-null    object
 2   Year                 300 non-null    int64
 3   Visitors_Millions    300 non-null    float64
 4   Revenue_Billion_USD  300 non-null    float64
 5   Average_Rating       300 non-null    float64
dtypes: float64(3), int64(1), object(2)
memory usage: 14.2+ KB

In [ ]:
df.describe() #To see mean, std, min, max statistic

              Year  Visitors_Millions  Revenue_Billion_USD  Average_Rating
count   300.000000         300.000000           300.000000      300.000000
mean   2019.333333          45.355167            62.617767        4.031533
std       2.888489          24.647344            34.861695        0.581776
min    2015.000000           0.570000             0.320000        3.010000
25%    2017.000000          26.082500            29.687500        3.520000
50%    2019.000000          47.005000            64.130000        4.045000
75%    2022.000000          65.965000            94.205000        4.540000
max    2024.000000          89.940000           119.560000        5.000000

In [ ]:
df.dtypes #To see Every column datatype

Country                 object
Category                object
Year                     int64
Visitors_Millions      float64
Revenue_Billion_USD    float64
Average_Rating         float64
dtype: object

In [ ]:
df.select_dtypes(include=['number']) # Divide the numeric column

     Year  Visitors_Millions  Revenue_Billion_USD  Average_Rating
0    2022              54.08                18.89            3.31
1    2018              13.29                78.18            3.11
2    2020               0.57               119.07            4.23
3    2023              26.57                73.50            3.28
4    2021              88.50                56.12            4.72
..    ...                ...                  ...             ...
295  2023               9.05                74.94            3.90
296  2015              66.45               103.56            3.43
297  2019              57.96                72.93            4.09
298  2023              44.96               118.54            3.27
299  2017              40.12                53.61            4.45

[300 rows x 4 columns]

In [ ]:
df.isnull() # Which column have missing value to see this coding .

,Country,Category,Year,Visitors_Millions,Revenue_Billion_USD,Average_Rating
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
295,False,False,False,False,False,False
296,False,False,False,False,False,False
297,False,False,False,False,False,False
298,False,False,False,False,False,False
299,False,False,False,False,False,False

In [ ]:
df.isnull().sum() # How many missing value have in this dataset.

Country                0
Category               0
Year                   0
Visitors_Millions      0
Revenue_Billion_USD    0
Average_Rating         0
dtype: int64

In [ ]:
df.isna() #Another method to check missing value method.

,Country,Category,Year,Visitors_Millions,Revenue_Billion_USD,Average_Rating
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
295,False,False,False,False,False,False
296,False,False,False,False,False,False
297,False,False,False,False,False,False
298,False,False,False,False,False,False
299,False,False,False,False,False,False

In [ ]:
df.dropna() # These row are delete who have missing value

,Country,Category,Year,Visitors_Millions,Revenue_Billion_USD,Average_Rating
0,Japan,Wildlife,2022,54.08,18.89,3.31
1,Australia,City,2018,13.29,78.18,3.11
2,Australia,Wildlife,2020,0.57,119.07,4.23
3,UAE,Religious,2023,26.57,73.50,3.28
4,Spain,Wildlife,2021,88.50,56.12,4.72
...,...,...,...,...,...,...
295,Japan,Cultural,2023,9.05,74.94,3.90
296,France,City,2015,66.45,103.56,3.43
297,India,Religious,2019,57.96,72.93,4.09
298,UAE,Beach,2023,44.96,118.54,3.27
299,USA,Cultural,2017,40.12,53.61,4.45

In [ ]:
df.fillna(0) # Missing value fill with (0)

,Country,Category,Year,Visitors_Millions,Revenue_Billion_USD,Average_Rating
0,Japan,Wildlife,2022,54.08,18.89,3.31
1,Australia,City,2018,13.29,78.18,3.11
2,Australia,Wildlife,2020,0.57,119.07,4.23
3,UAE,Religious,2023,26.57,73.50,3.28
4,Spain,Wildlife,2021,88.50,56.12,4.72
...,...,...,...,...,...,...
295,Japan,Cultural,2023,9.05,74.94,3.90
296,France,City,2015,66.45,103.56,3.43
297,India,Religious,2019,57.96,72.93,4.09
298,UAE,Beach,2023,44.96,118.54,3.27
299,USA,Cultural,2017,40.12,53.61,4.45

In [ ]:
df.drop_duplicates() # delete the duplicate row

,Country,Category,Year,Visitors_Millions,Revenue_Billion_USD,Average_Rating
0,Japan,Wildlife,2022,54.08,18.89,3.31
1,Australia,City,2018,13.29,78.18,3.11
2,Australia,Wildlife,2020,0.57,119.07,4.23
3,UAE,Religious,2023,26.57,73.50,3.28
4,Spain,Wildlife,2021,88.50,56.12,4.72
...,...,...,...,...,...,...
295,Japan,Cultural,2023,9.05,74.94,3.90
296,France,City,2015,66.45,103.56,3.43
297,India,Religious,2019,57.96,72.93,4.09
298,UAE,Beach,2023,44.96,118.54,3.27
299,USA,Cultural,2017,40.12,53.61,4.45

In [ ]:
df.columns

Index(['Country', 'Category', 'Year', 'Visitors_Millions',
       'Revenue_Billion_USD', 'Average_Rating'],
      dtype='object')

In [ ]:
df[['Average_Rating','Visitors_Millions']].mean() # Mean with select column .
#df.mean() #all column

Average_Rating        4.031533
Visitors_Millions    45.355167
dtype: float64

In [ ]:
#df.median()                       # middle value count

In [ ]:
df.mode()                         # One of the most calculate frequency

,Country,Category,Year,Visitors_Millions,Revenue_Billion_USD,Average_Rating
0,UAE,Beach,2016.0,23.10,3.24,3.07
1,NaN,NaN,NaN,55.83,29.45,3.52
2,NaN,NaN,NaN,NaN,76.44,4.45
3,NaN,NaN,NaN,NaN,108.02,4.68
4,NaN,NaN,NaN,NaN,119.56,NaN

In [ ]:
df[['Visitors_Millions']].std()                          # standard deviation

Visitors_Millions    24.647344
dtype: float64

In [ ]:
df.min()                          # minimum value

Country                Australia
Category               Adventure
Year                        2015
Visitors_Millions           0.57
Revenue_Billion_USD         0.32
Average_Rating              3.01
dtype: object

In [ ]:
df.max()                          # maximum value

Country                     USA
Category               Wildlife
Year                       2024
Visitors_Millions         89.94
Revenue_Billion_USD      119.56
Average_Rating              5.0
dtype: object

In [ ]:
#df.quantile()                     # quartile value count

In [ ]:
df["Revenue_Billion_USD"].unique() #How many unique value in column

array([ 18.89,  78.18, 119.07,  73.5 ,  56.12, 113.88,  27.86, 109.14,
        25.11, 111.21, 115.35,  33.86,  50.92,  87.54, 109.81,  39.16,
        14.53,  30.88,  76.44,  49.36,  19.51,  26.37,  13.38,  19.93,
        29.45, 116.62,  34.32,   4.16,  53.84,  28.67,  47.98, 103.03,
        27.33,  62.23, 105.31,  29.17,  42.04, 106.55,  69.77,  19.46,
         2.37,  65.2 ,  58.51,  59.2 ,   5.42, 114.38,  36.82, 112.35,
        80.6 ,  83.7 ,  97.25,  78.07,  69.48,   3.85,  92.45,  63.86,
        38.89,   3.24, 109.84,  76.66,  68.01,  37.51,  96.87, 106.42,
       102.81,  65.56,  24.96,  40.52,  31.43, 105.32,  50.93,  44.77,
        81.65,  59.69, 108.66,  75.89,  25.68,   7.1 ,  84.76,  12.31,
        84.81, 103.6 ,  85.04,  13.52,  92.11, 115.47,  52.47,   9.04,
        26.17, 108.16,  33.43,  43.37,  97.69,  87.14,  66.28, 118.48,
       101.09,   1.84,  66.74,  29.08,  80.67,  92.72,  95.06,  96.64,
        47.19,  94.08,  95.62,  55.2 ,  55.32,  49.52,  98.65,  14.65,
        39.75,  61.5 ,  89.84,  63.85,  82.52,  29.25, 100.92,  42.74,
        89.5 , 107.98,  28.62, 102.13,   2.39, 110.1 ,  98.54,  24.77,
        29.24,  18.69,  16.3 ,  30.71,  95.36,  87.76,  69.02,  95.98,
        62.86,  52.81,  52.76,   8.18,  75.4 , 107.29,  93.47, 105.24,
        72.55,  86.46,  71.96,  55.55,  73.45,  84.93,  12.69, 100.7 ,
        71.03,  94.58, 110.77,   4.14,   4.26,  21.53,  64.3 ,  96.01,
        35.43,  48.21, 113.54,  26.79,  21.59,  86.73,  48.89, 101.81,
        98.13,  32.31,  35.48,  67.98,  32.39,  50.72,  14.31,  59.8 ,
       108.02,  68.88,  42.59,  29.59,  35.8 ,  25.95, 101.6 ,  41.46,
        29.72,  70.91,  53.63,  91.13,  26.7 ,  66.79,  23.27,   6.77,
        14.64,  48.66,  38.39, 104.44,  95.89,  57.69,  50.25,  42.68,
         2.34,  26.35, 106.13,  27.95,  27.83,  99.18, 119.39, 119.56,
         4.38,  32.9 ,  97.18,  44.85,  26.58, 105.97,  81.43,  79.08,
        12.88, 105.51,  98.19,  14.08,  34.14, 112.48,  85.09, 104.61,
        46.16,   0.32,  54.28,  92.78, 113.25, 118.08,  78.27,  93.24,
        15.92,  57.89,  24.22,  95.75,  47.59,  93.63,  12.51,  93.14,
        42.21, 117.3 ,  80.51,  74.07,  75.11,  71.78,  87.03, 117.11,
         5.43,  26.62,  87.31,  92.17,  52.75,  78.67,  75.86,  72.3 ,
        52.57,  19.79,   1.28,  28.48,  17.66,  43.24,  84.71,   7.04,
        54.37,  82.65, 116.78,  63.96,  19.65,  21.42, 110.26,  79.01,
       104.52,  91.87,  95.78,  39.54,  53.95,  72.49, 103.63,  13.25,
        91.83,   1.11, 112.15,  34.33,  48.11,  21.94, 110.15,  63.27,
        71.31,  87.89,  74.94, 103.56,  72.93, 118.54,  53.61])

In [ ]:
df['Revenue_Billion_USD'].unique() #Ununique value count

array([ 18.89,  78.18, 119.07,  73.5 ,  56.12, 113.88,  27.86, 109.14,
        25.11, 111.21, 115.35,  33.86,  50.92,  87.54, 109.81,  39.16,
        14.53,  30.88,  76.44,  49.36,  19.51,  26.37,  13.38,  19.93,
        29.45, 116.62,  34.32,   4.16,  53.84,  28.67,  47.98, 103.03,
        27.33,  62.23, 105.31,  29.17,  42.04, 106.55,  69.77,  19.46,
         2.37,  65.2 ,  58.51,  59.2 ,   5.42, 114.38,  36.82, 112.35,
        80.6 ,  83.7 ,  97.25,  78.07,  69.48,   3.85,  92.45,  63.86,
        38.89,   3.24, 109.84,  76.66,  68.01,  37.51,  96.87, 106.42,
       102.81,  65.56,  24.96,  40.52,  31.43, 105.32,  50.93,  44.77,
        81.65,  59.69, 108.66,  75.89,  25.68,   7.1 ,  84.76,  12.31,
        84.81, 103.6 ,  85.04,  13.52,  92.11, 115.47,  52.47,   9.04,
        26.17, 108.16,  33.43,  43.37,  97.69,  87.14,  66.28, 118.48,
       101.09,   1.84,  66.74,  29.08,  80.67,  92.72,  95.06,  96.64,
        47.19,  94.08,  95.62,  55.2 ,  55.32,  49.52,  98.65,  14.65,
        39.75,  61.5 ,  89.84,  63.85,  82.52,  29.25, 100.92,  42.74,
        89.5 , 107.98,  28.62, 102.13,   2.39, 110.1 ,  98.54,  24.77,
        29.24,  18.69,  16.3 ,  30.71,  95.36,  87.76,  69.02,  95.98,
        62.86,  52.81,  52.76,   8.18,  75.4 , 107.29,  93.47, 105.24,
        72.55,  86.46,  71.96,  55.55,  73.45,  84.93,  12.69, 100.7 ,
        71.03,  94.58, 110.77,   4.14,   4.26,  21.53,  64.3 ,  96.01,
        35.43,  48.21, 113.54,  26.79,  21.59,  86.73,  48.89, 101.81,
        98.13,  32.31,  35.48,  67.98,  32.39,  50.72,  14.31,  59.8 ,
       108.02,  68.88,  42.59,  29.59,  35.8 ,  25.95, 101.6 ,  41.46,
        29.72,  70.91,  53.63,  91.13,  26.7 ,  66.79,  23.27,   6.77,
        14.64,  48.66,  38.39, 104.44,  95.89,  57.69,  50.25,  42.68,
         2.34,  26.35, 106.13,  27.95,  27.83,  99.18, 119.39, 119.56,
         4.38,  32.9 ,  97.18,  44.85,  26.58, 105.97,  81.43,  79.08,
        12.88, 105.51,  98.19,  14.08,  34.14, 112.48,  85.09, 104.61,
        46.16,   0.32,  54.28,  92.78, 113.25, 118.08,  78.27,  93.24,
        15.92,  57.89,  24.22,  95.75,  47.59,  93.63,  12.51,  93.14,
        42.21, 117.3 ,  80.51,  74.07,  75.11,  71.78,  87.03, 117.11,
         5.43,  26.62,  87.31,  92.17,  52.75,  78.67,  75.86,  72.3 ,
        52.57,  19.79,   1.28,  28.48,  17.66,  43.24,  84.71,   7.04,
        54.37,  82.65, 116.78,  63.96,  19.65,  21.42, 110.26,  79.01,
       104.52,  91.87,  95.78,  39.54,  53.95,  72.49, 103.63,  13.25,
        91.83,   1.11, 112.15,  34.33,  48.11,  21.94, 110.15,  63.27,
        71.31,  87.89,  74.94, 103.56,  72.93, 118.54,  53.61])

In [ ]:
df['Revenue_Billion_USD'].value_counts()

Revenue_Billion_USD
3.24      2
76.44     2
29.45     2
119.56    2
108.02    2
         ..
101.09    1
118.48    1
66.28     1
87.14     1
95.06     1
Name: count, Length: 295, dtype: int64

In [ ]:
df.groupby('Country') #Group analysis by column

In [ ]:
df.columns

Index(['Country', 'Category', 'Year', 'Visitors_Millions',
       'Revenue_Billion_USD', 'Average_Rating'],
      dtype='object')

In [ ]:
#df.groupby("Country")['sales'].mean() # Average sales by city

In [ ]:
df[['Visitors_Millions']].corr() # To see feature correlation only numeric column .

                   Visitors_Millions
Visitors_Millions                1.0

In [ ]:
#plt.plot()                        # To show line plot (trend )
#plt.scatter()                     # To show scatter plot (relation)
#plt.hist()                        # To show histogram (distribution)
#plt.bar()                         # To Show bar chart (category compare)
#sns.countplot()                   # To Show category frequency
#sns.boxplot()                     # To Show  outlier detect
#sns.violinplot()                  # To Show distribution + density
#sns.heatmap()                     # To Show correlation visualize
#sns.pairplot()                    # To Show all numeric feature relation